"""remaining schema tables 6-43

Revision ID: 2b5cc45b943b
Revises: 002_profiles
Create Date: 2026-08-20 12:23:04.602186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5cc45b943b'
down_revision: Union[str, Sequence[str], None] = '002_profiles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    new_enums = [
        ("reward_offer_kind", ("percent_off", "free_minutes", "priority_match")),
        ("notification_type", ("session_request", "session_reminder", "review", "payout", "system", "rewards")),
        ("day_of_week", ("mon", "tue", "wed", "thu", "fri", "sat", "sun")),
        ("mood_kind", ("great", "okay", "anxious", "sad", "angry")),
        ("training_status", ("not_started", "in_progress", "completed")),
        ("payout_method_type", ("bank", "paypal")),
        ("session_request_status", ("pending", "accepted", "declined", "expired", "cancelled")),
        ("session_time_mode", ("instant", "nearest", "scheduled")),
        ("call_mode", ("voice", "video")),
        ("invite_status", ("pending", "joined", "first_session", "booked_call")),
        ("payout_status", ("pending", "completed", "failed")),
        ("session_status", ("upcoming", "live", "completed", "cancelled", "missed")),
        ("payment_status", ("pending", "paid", "refunded", "failed")),
        ("reported_role", ("ventor", "listener")),
        ("report_reason", (
            "inappropriate_behavior", "harassment", "hate_speech", "safety_concern",
            "not_listening", "technical_issue", "other",
        )),
        ("ledger_entry_type", (
            "session_earning", "tip", "penalty", "payout", "payout_reversal", "adjustment",
        )),
    ]
    for name, values in new_enums:
        postgresql.ENUM(*values, name=name, create_type=False).create(bind, checkfirst=True)

    op.create_table('achievements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title_key', sa.String(length=128), nullable=False),
    sa.Column('subtitle_key', sa.String(length=128), nullable=False),
    sa.Column('description_key', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boundaries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comfort_areas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('topic_group', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('name_ar', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_experiences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('reward_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', postgresql.ENUM('percent_off', 'free_minutes', 'priority_match', name='reward_offer_kind', create_type=False), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('percent_off', sa.Integer(), nullable=True),
    sa.Column('free_minutes', sa.Integer(), nullable=True),
    sa.Column('min_tier', postgresql.ENUM('starter', 'rising', 'trusted', 'expert', 'elite', name='earnings_tier', create_type=False), nullable=True),
    sa.Column('max_tier', postgresql.ENUM('starter', 'rising', 'trusted', 'expert', 'elite', name='earnings_tier', create_type=False), nullable=True),
    sa.Column('is_welcome_gift', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('training_modules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title_key', sa.String(length=128), nullable=False),
    sa.Column('content_url', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('session_request', 'session_reminder', 'review', 'payout', 'system', 'rewards', name='notification_type', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_deleted', 'notifications', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_notifications_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_table('invite_codes',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('invite_link', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('ventor_id')
    )
    op.create_table('listener_availability_settings',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('accept_instant_calls', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_length_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('break_length_minutes', sa.Integer(), server_default='15', nullable=False),
    sa.Column('time_zone_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id')
    )
    op.create_table('listener_availability_slots',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('day', postgresql.ENUM('mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', name='day_of_week', create_type=False), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_slot_time_range'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listener_availability_slots_listener_day', 'listener_availability_slots', ['listener_id', 'day'], unique=False)
    op.create_table('listener_boundaries',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('boundary_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['boundary_id'], ['boundaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id', 'boundary_id')
    )
    op.create_table('listener_comfort_areas',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('comfort_area_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['comfort_area_id'], ['comfort_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id', 'comfort_area_id')
    )
    op.create_table('listener_languages',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id', 'language_id')
    )
    op.create_table('listener_life_experiences',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('life_experience_id', sa.String(length=64), nullable=False),
    sa.Column('custom_label', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['life_experience_id'], ['life_experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id', 'life_experience_id')
    )
    op.create_table('listener_notification_preferences',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('new_session_requests', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_15_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_10_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_5_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('reviews_feedback', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('tips_earnings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('promotions_updates', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id')
    )
    op.create_table('listener_privacy_settings',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('show_online_status', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_languages', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_comfort_areas', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_experience_and_ratings', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_boundaries', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('visible_in_all_countries', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('visible_countries', postgresql.ARRAY(sa.String(length=2)), nullable=True),
    sa.Column('allow_search_indexing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id')
    )
    op.create_table('listener_training_progress',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('status', postgresql.ENUM('not_started', 'in_progress', 'completed', name='training_status', create_type=False), server_default='not_started', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id', 'module_id')
    )
    op.create_table('listener_wallets',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('pending_balance', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('lifetime_earned', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listener_id')
    )
    op.create_table('mood_checkins',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('mood', postgresql.ENUM('great', 'okay', 'anxious', 'sad', 'angry', name='mood_kind', create_type=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ventor_id', 'checkin_date', name='uq_mood_checkins_ventor_date')
    )
    op.create_index('ix_mood_checkins_ventor_id', 'mood_checkins', ['ventor_id'], unique=False)
    op.create_table('payout_methods',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('bank', 'paypal', name='payout_method_type', create_type=False), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('account_holder_name', sa.String(length=120), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('iban_or_account', sa.String(length=64), nullable=True),
    sa.Column('swift_code', sa.String(length=32), nullable=True),
    sa.Column('paypal_email', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payout_methods_listener_id', 'payout_methods', ['listener_id'], unique=False)
    op.create_table('reward_trades',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('points_spent', sa.Integer(), nullable=False),
    sa.Column('is_welcome_gift', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['reward_offers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_trades_ventor_id', 'reward_trades', ['ventor_id'], unique=False)
    op.create_table('session_requests',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('listener_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', 'expired', 'cancelled', name='session_request_status', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('chosen_reason', sa.String(length=120), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('time_mode', postgresql.ENUM('instant', 'nearest', 'scheduled', name='session_time_mode', create_type=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_mode', postgresql.ENUM('voice', 'video', name='call_mode', create_type=False), nullable=False),
    sa.Column('speech_language', sa.String(length=64), nullable=False),
    sa.Column('voice_change_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_instant', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('reward_offer_id', sa.UUID(), nullable=True),
    sa.Column('quoted_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reward_offer_id'], ['reward_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_requests_instant_status_created', 'session_requests', ['is_instant', 'status', 'created_at'], unique=False)
    op.create_index('ix_session_requests_listener_status', 'session_requests', ['listener_id', 'status'], unique=False)
    op.create_index('ix_session_requests_ventor_status', 'session_requests', ['ventor_id', 'status'], unique=False)
    op.create_table('ventor_achievements',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ventor_id', 'achievement_id')
    )
    op.create_table('ventor_favorites',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ventor_id', 'listener_id')
    )
    op.create_table('ventor_interests',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('comfort_area_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['comfort_area_id'], ['comfort_areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ventor_id', 'comfort_area_id')
    )
    op.create_table('ventor_notification_preferences',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_30_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_15_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_10_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('session_reminder_5_min', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rewards_updates', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('promotions_updates', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ventor_id')
    )
    op.create_table('ventor_privacy_settings',
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('show_mood_journey', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_achievements', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_stats', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_favorite_listeners', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_listener_discovery', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ventor_id')
    )
    op.create_table('invite_events',
    sa.Column('invite_code_id', sa.UUID(), nullable=False),
    sa.Column('inviter_ventor_id', sa.UUID(), nullable=False),
    sa.Column('invitee_user_id', sa.UUID(), nullable=True),
    sa.Column('invitee_display_name', sa.String(length=120), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'joined', 'first_session', 'booked_call', name='invite_status', create_type=False), nullable=False),
    sa.Column('points_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invite_code_id'], ['invite_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inviter_ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invite_events_inviter_status', 'invite_events', ['inviter_ventor_id', 'status'], unique=False)
    op.create_table('payouts',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('payout_method_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='payout_status', create_type=False), nullable=False),
    sa.Column('method_label', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_method_id'], ['payout_methods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payouts_listener_id', 'payouts', ['listener_id'], unique=False)
    op.create_table('sessions',
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('upcoming', 'live', 'completed', 'cancelled', 'missed', name='session_status', create_type=False), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('time_mode', postgresql.ENUM('instant', 'nearest', 'scheduled', name='session_time_mode', create_type=False), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_mode', postgresql.ENUM('voice', 'video', name='call_mode', create_type=False), nullable=False),
    sa.Column('speech_language', sa.String(length=64), nullable=False),
    sa.Column('voice_change_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_instant', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('chosen_reason', sa.String(length=120), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('listener_history_outcome', sa.String(length=16), nullable=True),
    sa.Column('missed_by_listener', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('call_channel_id', sa.String(length=128), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['session_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('ix_sessions_listener_status_scheduled', 'sessions', ['listener_id', 'status', 'scheduled_at'], unique=False)
    op.create_index('ix_sessions_ventor_status_scheduled', 'sessions', ['ventor_id', 'status', 'scheduled_at'], unique=False)
    op.create_foreign_key(
        'fk_session_requests_session_id',
        'session_requests',
        'sessions',
        ['session_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('promo_redemptions',
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_listener_feedback',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('felt_heard', sa.Boolean(), nullable=False),
    sa.Column('talk_again', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='ck_session_listener_feedback_stars'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_payments',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('session_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('voice_change_fee', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tip_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'refunded', 'failed', name='payment_status', create_type=False), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('promo_code_id', sa.UUID(), nullable=True),
    sa.Column('reward_offer_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reward_offer_id'], ['reward_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_ratings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ventor_id', sa.UUID(), nullable=False),
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('tip_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('stars >= 1 AND stars <= 5', name='ck_session_ratings_stars'),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ventor_id'], ['ventor_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('ix_session_ratings_listener_id', 'session_ratings', ['listener_id'], unique=False)
    op.create_table('session_reports',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('reporter_user_id', sa.UUID(), nullable=False),
    sa.Column('reported_role', postgresql.ENUM('ventor', 'listener', name='reported_role', create_type=False), nullable=False),
    sa.Column('reason', postgresql.ENUM('inappropriate_behavior', 'harassment', 'hate_speech', 'safety_concern', 'not_listening', 'technical_issue', 'other', name='report_reason', create_type=False), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_reports_session_id', 'session_reports', ['session_id'], unique=False)
    op.create_table('wallet_ledger_entries',
    sa.Column('listener_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('session_earning', 'tip', 'penalty', 'payout', 'payout_reversal', 'adjustment', name='ledger_entry_type', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['listener_id'], ['listener_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_wallet_ledger_entries_listener_created', 'wallet_ledger_entries', ['listener_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_ventor_profiles_active_reward_offer_id', 'ventor_profiles', 'reward_offers', ['active_reward_offer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ventor_profiles_active_reward_offer_id', 'ventor_profiles', type_='foreignkey')
    op.drop_constraint('fk_session_requests_session_id', 'session_requests', type_='foreignkey')
    op.drop_index('ix_wallet_ledger_entries_listener_created', table_name='wallet_ledger_entries')
    op.drop_table('wallet_ledger_entries')
    op.drop_index('ix_session_reports_session_id', table_name='session_reports')
    op.drop_table('session_reports')
    op.drop_index('ix_session_ratings_listener_id', table_name='session_ratings')
    op.drop_table('session_ratings')
    op.drop_table('session_payments')
    op.drop_table('session_listener_feedback')
    op.drop_table('promo_redemptions')
    op.drop_index('ix_sessions_ventor_status_scheduled', table_name='sessions')
    op.drop_index('ix_sessions_listener_status_scheduled', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_payouts_listener_id', table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('ix_invite_events_inviter_status', table_name='invite_events')
    op.drop_table('invite_events')
    op.drop_table('ventor_privacy_settings')
    op.drop_table('ventor_notification_preferences')
    op.drop_table('ventor_interests')
    op.drop_table('ventor_favorites')
    op.drop_table('ventor_achievements')
    op.drop_index('ix_session_requests_ventor_status', table_name='session_requests')
    op.drop_index('ix_session_requests_listener_status', table_name='session_requests')
    op.drop_index('ix_session_requests_instant_status_created', table_name='session_requests')
    op.drop_table('session_requests')
    op.drop_index('ix_reward_trades_ventor_id', table_name='reward_trades')
    op.drop_table('reward_trades')
    op.drop_index('ix_payout_methods_listener_id', table_name='payout_methods')
    op.drop_table('payout_methods')
    op.drop_index('ix_mood_checkins_ventor_id', table_name='mood_checkins')
    op.drop_table('mood_checkins')
    op.drop_table('listener_wallets')
    op.drop_table('listener_training_progress')
    op.drop_table('listener_privacy_settings')
    op.drop_table('listener_notification_preferences')
    op.drop_table('listener_life_experiences')
    op.drop_table('listener_languages')
    op.drop_table('listener_comfort_areas')
    op.drop_table('listener_boundaries')
    op.drop_index('ix_listener_availability_slots_listener_day', table_name='listener_availability_slots')
    op.drop_table('listener_availability_slots')
    op.drop_table('listener_availability_settings')
    op.drop_table('invite_codes')
    op.drop_index('ix_notifications_user_read_created', table_name='notifications', postgresql_ops={'created_at': 'DESC'})
    op.drop_index('ix_notifications_user_deleted', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('training_modules')
    op.drop_table('reward_offers')
    op.drop_table('promo_codes')
    op.drop_table('life_experiences')
    op.drop_table('languages')
    op.drop_table('comfort_areas')
    op.drop_table('boundaries')
    op.drop_table('achievements')
    # ### end Alembic commands ###
